"""Running a strip's effects as its own PipeWire filter chain.

Each strip with effects gets a config file and a `pipewire -c` process of its
own, which is the pattern PipeWire itself ships a systemd unit for. Two reasons
it is worth a process per strip rather than adding the chain to the mixer's own
drop-in:

* Changing which effects are on rewrites the graph, and a graph only takes
  effect when its host starts. Restarting one strip's host blips that strip;
  rewriting the shared drop-in would restart the whole audio server and cut
  every other strip with it, the way adding a channel does.
* A crash takes one chain down, not the mixer.

Control *values* need none of that. Every control port of a running chain is a
node property, settable live, which is why a slider here is immediate while a
switch costs a restart.
"""
import os
import shutil
import subprocess

from .. import settings
from ..audio import effects as effects_module

# Chain nodes sit mid-graph, between a microphone and its virtual sink, and the
# mixer links them itself. Both keys matter and neither implies the other:
# passive stops a link holding the node running, while autoconnect = false stops
# the session manager wiring it to the default device. Without the latter,
# WirePlumber connected the strip's own published microphone into the chain's
# input - chain to sink to chain, a feedback loop.
_CONF_TEMPLATE = """# Generated by Pipeworks. Edits here are overwritten.
context.properties = {{
    log.level = 0
}}

context.spa-libs = {{
    audio.convert.* = audioconvert/libspa-audioconvert
    support.*       = support/libspa-support
}}

context.modules = [
    {{ name = libpipewire-module-rt
        args = {{
            nice.level = -11
        }}
        flags = [ ifexists nofail ]
    }}
    {{ name = libpipewire-module-protocol-native }}
    {{ name = libpipewire-module-client-node }}
    {{ name = libpipewire-module-adapter }}
    {{ name = libpipewire-module-filter-chain
        args = {{
            node.description = "{description}"
            media.name       = "{description}"
            filter.graph = {{
                nodes = [
{nodes}
                ]
                links = [
{links}
                ]
            }}
            audio.channels = 2
            audio.position = [ FL FR ]
            capture.props = {{
                node.name        = "{in_node}"
                node.passive     = true
                node.autoconnect = false
            }}
            playback.props = {{
                node.name        = "{out_node}"
                node.passive     = true
                node.autoconnect = false
            }}
        }}
    }}
]
"""


class FilterChainHost:
    """Owns the config files and processes for every strip's effects."""

    def __init__(self, runner, directory=settings.FX_CONF_DIR):
        self._runner = runner
        self._directory = directory
        self._processes = {}
        self.clear_strays()

    def clear_strays(self):
        """Kills chain hosts left behind by a previous run.

        The processes are tracked in memory, so a daemon that was killed rather
        than stopped never gets to terminate them, and a restart would leave one
        running per strip - unowned, still holding its links, and invisible to
        the new daemon's own bookkeeping.
        """
        self._runner.run("pkill", "-f", f"pipewire -c {self._directory}")

    # ------------------------------------------------------------------
    # Naming. Front ends and the graph both need to agree on these.

    @staticmethod
    def input_node(strip_id):
        return f"{settings.FX_NODE_PREFIX}_{strip_id}_in"

    @staticmethod
    def output_node(strip_id):
        return f"{settings.FX_NODE_PREFIX}_{strip_id}_out"

    def conf_path(self, strip_id):
        return os.path.join(self._directory, f"{strip_id}.conf")

    # ------------------------------------------------------------------

    def apply(self, strip_id, label, strip_effects):
        """Brings one strip's chain in line with its config.

        Returns True when a chain is running afterwards, so the caller knows
        whether to route through it or straight past it.
        """
        nodes, links = effects_module.build_graph(strip_effects)
        if not nodes:
            self.stop(strip_id)
            return False

        wanted = self._render(strip_id, label, nodes, links)
        existing = self._read(self.conf_path(strip_id))
        if wanted != existing or not self.running(strip_id):
            self._write(self.conf_path(strip_id), wanted)
            self.restart(strip_id)
        return True

    def running(self, strip_id):
        process = self._processes.get(strip_id)
        return process is not None and process.poll() is None

    def restart(self, strip_id):
        self.stop(strip_id)
        self.start(strip_id)

    def start(self, strip_id):
        path = self.conf_path(strip_id)
        if not os.path.exists(path):
            return
        binary = shutil.which("pipewire")
        if not binary:
            return
        self._processes[strip_id] = subprocess.Popen(
            [binary, "-c", path],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )

    def stop(self, strip_id):
        process = self._processes.pop(strip_id, None)
        if process is None or process.poll() is not None:
            return
        process.terminate()
        try:
            process.wait(timeout=3)
        except subprocess.TimeoutExpired:
            process.kill()

    def stop_all(self):
        for strip_id in list(self._processes):
            self.stop(strip_id)

    def forget(self, strip_id):
        """Stops a chain and removes its config, for a strip being deleted."""
        self.stop(strip_id)
        path = self.conf_path(strip_id)
        if os.path.exists(path):
            os.remove(path)

    # ------------------------------------------------------------------
    # Live control

    def set_control(self, strip_id, port, value):
        """Sets one control port on a running chain, without restarting it."""
        node_id = self._node_id(self.input_node(strip_id))
        if node_id is None:
            return False
        self._runner.run(
            "pw-cli", "s", str(node_id), "Props",
            '{ params = [ "%s" %s ] }' % (port, float(value)),
        )
        return True

    def _node_id(self, node_name):
        result = self._runner.capture("pw-dump")
        if result.returncode != 0:
            return None
        import json

        try:
            objects = json.loads(result.stdout)
        except json.JSONDecodeError:
            return None
        for entry in objects:
            props = ((entry.get("info") or {}).get("props")) or {}
            if props.get("node.name") == node_name:
                return entry.get("id")
        return None

    # ------------------------------------------------------------------

    def _render(self, strip_id, label, nodes, links):
        rendered_nodes = "\n".join(self._node_block(node) for node in nodes)
        rendered_links = "\n".join(
            f'                    {{ output = "{source}:{source_port}" '
            f'input = "{dest}:{dest_port}" }}'
            for source, source_port, dest, dest_port in links
        )
        return _CONF_TEMPLATE.format(
            description=f"Pipeworks {label} effects",
            nodes=rendered_nodes,
            links=rendered_links,
            in_node=self.input_node(strip_id),
            out_node=self.output_node(strip_id),
        )

    @staticmethod
    def _node_block(node):
        parts = [
            "                    {",
            f'                        type = {node["type"]}',
            f'                        name = {node["name"]}',
        ]
        if node.get("plugin"):
            parts.append(f'                        plugin = "{node["plugin"]}"')
        if node.get("label"):
            parts.append(f'                        label = {node["label"]}')
        if node.get("control"):
            controls = " ".join(
                f'"{port}" = {value}' for port, value in node["control"].items()
            )
            parts.append(f"                        control = {{ {controls} }}")
        parts.append("                    }")
        return "\n".join(parts)

    @staticmethod
    def _read(path):
        if not os.path.exists(path):
            return None
        with open(path) as handle:
            return handle.read()

    def _write(self, path, content):
        os.makedirs(self._directory, exist_ok=True)
        with open(path, "w") as handle:
            handle.write(content)
